import { describe, expect, it } from 'vitest'
import { renderWordFamiliesModule } from './renderWordFamiliesModule'

describe('renderWordFamiliesModule', () => {
  it('renders a deterministic, game-consumable TypeScript module', () => {
    const source = renderWordFamiliesModule({
      families: [{ stem: 'play', words: ['display', 'play', 'player'] }],
      rejected: [],
    })
    expect(source).toBe(
      [
        '// Generated by scripts/generate-word-data.ts — do not edit.',
        '// Inputs: data/words/words_alpha.txt (English word list) and data/stems.txt (curated stems),',
        '// vetted at build time against the minimum Word family size; rejected stems are omitted.',
        "import type { WordFamilies } from '../domain/wordFamily'",
        '',
        'export const WORD_FAMILIES: WordFamilies = {',
        '  "play": {',
        '    "stem": "play",',
        '    "words": [',
        '      "display",',
        '      "play",',
        '      "player"',
        '    ]',
        '  }',
        '}',
        '',
      ].join('\n'),
    )
  })

  it('renders multiple stems in input order', () => {
    const source = renderWordFamiliesModule({
      families: [
        { stem: 'play', words: ['play', 'player'] },
        { stem: 'port', words: ['port', 'sport'] },
      ],
      rejected: [],
    })
    expect(source.indexOf('"play"')).toBeLessThan(source.indexOf('"port"'))
  })
})
