import type { WordFamilies } from '../domain/wordFamily'
import type { PipelineResult } from './generateWordFamilies'

export function renderWordFamiliesModule(result: PipelineResult): string {
  const families: WordFamilies = {}
  for (const family of result.families) {
    families[family.stem] = family
  }
  const header = [
    '// Generated by scripts/generate-word-data.ts — do not edit.',
    '// Inputs: data/words/words_alpha.txt (English word list) and data/stems.txt (curated stems),',
    '// vetted at build time against the minimum Word family size; rejected stems are omitted.',
  ].join('\n')
  const body = JSON.stringify(families, null, 2)
  return `${header}\nimport type { WordFamilies } from '../domain/wordFamily'\n\nexport const WORD_FAMILIES: WordFamilies = ${body}\n`
}
